apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${DC_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE}
  storageClassName: ocs-storagecluster-cephfs
