kind: DeploymentConfig
apiVersion: v1
spec:
  template:
    spec:
      containers:
        - name: "nsqd"
          image: "nsqio/nsq"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              memory: "150Mi"

          command:
            - '/nsqd'
          args:
            - '--lookupd-tcp-address=${NSQ_LOOKUP}'
            - '--data-path=/data/${DC_NAME}'
            - '--broadcast-address=${DC_NAME}-nsq'

          volumeMounts:
            - mountPath: "/data/${DC_NAME}"
              name: nsq-data
      volumes:
        - name: nsq-data
          persistentVolumeClaim:
            claimName: pvc-nsq-data
