name: Python Unit Testing

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Unit test
        run: |
          coverage run -m unittest discover -s tests --pattern "*.py"
          coverage xml

      - name: Python Cov
          uses: orgoro/coverage@v2
          with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}